global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  # Exposes port for data to be queried by grafana, can be viewed at localhost:9090/metrics, or queried at localhost:9090/graph
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
      
  # Scrapes all of the container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:${CA_ADVISOR_PORT}']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # Adds the data from prom/node-exporter to localhost:9090/graph
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
